version: '3.7'

networks:
    jenkins-nexus:
        driver: bridge  
services:
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
            - 8081:8080
            - 50000:50000
        container_name: jenkins
        networks:
            - jenkins-nexus
        volumes:
            - jenkins_home:/var/jenkins_home
    nexus:
        image: sonatype/nexus3
        ports:
            - 8082:8081
        container_name: nexus
        networks: 
            - jenkins-nexus 
        volumes:
            - nexus_data:/sonatype-work
volumes:
    jenkins_home: 
    nexus_data:
